name: CI

on: [push, pull_request]

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opam_file:
          - 'coq-autosubst-ocaml.opam'
        image:
          - 'coqorg/coq:dev-ocaml-4.14.1-flambda'
      fail-fast: false  # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: coq-community/docker-coq-action@v1
        with:
          custom_image: ${{ matrix.image }}
          opam_file: ${{ matrix.opam_file }}
          before_script: |
            startGroup "fix permission issues"
              sudo chown -R coq:coq .
            endGroup
          after_script: |
            startGroup "Run benchmarks"
              ./generate-opam.sh
              cd ./case-studies/
              make
            endGroup
